"""add column experience,status to employees

Revision ID: 1a7c56706f2f
Revises: c93f12ef41cb
Create Date: 2026-06-10 14:07:36.416346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a7c56706f2f"
down_revision: Union[str, Sequence[str], None] = "c93f12ef41cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_STATUS_ENUM = sa.Enum("Active", "Inactive", "Probation", name="status")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _STATUS_ENUM.create(op.get_bind(), checkfirst=True)

    op.add_column("employees", sa.Column("experience", sa.Integer(), nullable=True))
    op.execute("UPDATE employees SET experience = 1 WHERE experience IS NULL")
    op.alter_column("employees", "status", nullable=False)

    op.add_column(
        "employees",
        sa.Column(
            "status",
            sa.Enum("Active", "Inactive", "Probation", name="status"),
            nullable=True,
        ),
    )
    op.execute("UPDATE employees SET status = 'Active' WHERE status IS NULL")
    op.alter_column("employees", "status", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "status")
    op.drop_column("employees", "experience")
    # ### end Alembic commands ###
