"""Add passowrd hash

Revision ID: 7647617d92f2
Revises: fc044ecff28b
Create Date: 2026-05-29 16:01:37.348070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7647617d92f2'
down_revision: Union[str, Sequence[str], None] = 'fc044ecff28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Changing a type in postal code 
    op.add_column('addresses', sa.Column('postal_code', sa.String(length=10), nullable=False))
    op.execute('UPDATE addresses SET postal_code = psotal_code')
    op.drop_column('addresses', 'psotal_code')

    op.add_column('employees', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.execute("UPDATE employees SET password_hash = 'placeholder' WHERE password_hash IS NULL")
    op.alter_column("employees", "password_hash", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password_hash')

    op.add_column('addresses', sa.Column('psotal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('addresses', 'postal_code')
    # ### end Alembic commands ###
