"""add role to employee

Revision ID: c93f12ef41cb
Revises: 9c6206ae4ee5
Create Date: 2026-06-01 14:11:56.482308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93f12ef41cb'
down_revision: Union[str, Sequence[str], None] = '9c6206ae4ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ROLE_ENUM = sa.Enum('UI', 'UX', 'Developer', 'HR', name='employeerole')

def upgrade() -> None:
    """Upgrade schema."""

    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role', _ROLE_ENUM, server_default='Developer', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'role')
    # ### end Alembic commands ###
